version: "3"
services:
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
  web:
    build:
      context: carrental
      dockerfile: web-Dockerfile
    restart: on-failure
    ports:
      - "80:80"
  backend:
    build:
      context: carrental
      dockerfile: api-Dockerfile
    restart: on-failure
    ports:
      - "3333:3333"
#  db:
#    image: postgres:13-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=docker
#    ports:
#      - '5432:5432'
#    volumes:
#      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local